# Generated by Django 4.2.4 on 2023-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoinfoDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("form", models.CharField(blank=True, max_length=100, null=True)),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                ("dim", models.CharField(blank=True, max_length=100, null=True)),
                ("episodes", models.IntegerField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("episode_start", models.IntegerField(blank=True, null=True)),
                ("episode_end", models.IntegerField(blank=True, null=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("date_watch_start", models.DateField(blank=True, null=True)),
                ("date_watch_end", models.DateField(blank=True, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "noinfo_detail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NoinfoTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(blank=True, max_length=100, null=True)),
                ("state_view", models.CharField(blank=True, max_length=100, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("universe", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "noinfo_theme",
                "managed": True,
            },
        ),
    ]
